- product:
  id: "1"
  img: "./assets/img/product/p7.jpg"
  cat: สับปะรดกวน
  name: ร้าน “กวนเก่งเป็นสับปะรด”
  title: สับปะรดกวน
  discription:   กล่องเล็ก 200 กรัม ราคา 50 บาท<br> กล่องใหญ่ 500 กรัม ราคา 120 บาท
  location: กลุ่มผลิตภัณฑ์แปรรูปเขาไมแกว
  contact: 089-814-2213
  owner: คุณเก่ง
  
- product:
  id: "2"
  img: "./assets/img/product/p4.jpg"
  cat: ข้าวต้มมัด
  name: ร้าน “ข้าวต้มมัดยายพน”
  title: ข้าวต้มมัดไส้กล้วย
  discription:  กล่องละ 50 บาท มี 4 มัด
  location: ขายที่ตลาดนัดเขาไมแกวหลังร้านอาหารครัวลุงเนียร <br>ทุกวันพฤหัสบดีและวันเสาร์
  contact: 090-387-5631
  owner: คุณส้ม
  
- product:
  id: 3
  img: "./assets/img/product/p1.jpg"
  cat: น้ำสลัดสมุนไพร
  name: ร้าน “ภูริทัตน้ำสลัด”
  title: น้ำสลัดจากสมุนไพร มี 2 สูตร <br>1.น้ำสลัดสูตรผสมน้ำส้มที่สกัดจากสับปะรด <br>2. น้ำสลัดจากผลสดส้มจี๊ด
  discription:   กระปุกละ 25 บาท ขนาด 4 ออนซ์
  location: ขายที่ตลาดนัดเขาไมแกวหลังร้านอาหารครัวลุงเนียร<br> ทุกวันพฤหัสบดีและวันเสาร์
  contact: 090-387-5631
  owner: คุณส้ม
  
- product:
  id: "4"
  img: "./assets/img/product/p3.jpg"
  cat: สับปะรดหยี
  name: ร้าน “เจ๊ส้ม สับปะรดหยี”
  title: สับปะรดหยี
  discription:  กล่องละ 20 บาท ประมาณ 10 เม็ด
  location: รับสั่งทำจำหน่ายนอกสถานที่
  contact: 085-355-2023
  owner: คุณส้ม
  
- product:
  id: "2"
  img: "./assets/img/product/p2.jpg"
  cat: สบู่สับปะรด
  name: ร้าน “นฤมล สบู่สับปะรด”
  title: สบู่สับปะรด, สครับขัดผิวสับปะรด, สบู่มะขามขมิ้น
  discription:   สบู่สับปะรด ขนาด 90 กรัม ก้อนละ 60 บาท <br>สครับขัดผิวสับปะรด ขนาด 300 กรัม กระปุกละ 200 บาท <br>สบู่มะขามขมิ้น ขนาด 90 กรัม ก้อนละ 60 บาท
  location: ตลาดบน ตำบลโป่ง
  contact: 063-391-7899
  owner: คุณนฤมล
  
- product:
  id: "6"
  img: "./assets/img/product/p5.jpg"
  cat: น้ำอ้อย
  name: ร้าน “น้ำอ้อยพี่ภัทร”
  title: น้ำอ้อย
  discription:  ขวดละ 10 บาท
  location: ศูนย์โอทอปชุมชนเขาไมแกว
  contact: 094-179-5438
  owner: คุณภัทร
  
- product:
  id: "7"
  img: "./assets/img/product/p6.jpg"
  cat: วุ้นมะพร้าว
  name: ร้าน “วุ้นมะพร้าวแม่บุญมา”
  title: วุ้นมะพร้าว
  discription:  กล่องละ 20 บาท
  location: ศูนย์โอทอปชุมชนเขาไมแกว
  contact: 090-134-4191
  owner: คุณวิฑูรย์
  
- product:
  id: "8"
  img: "./assets/img/product/p8.jpg"
  cat: มะพร้าวแก้ว
  name: ร้าน “แม่พูลสุขมะพร้าวแก้ว”
  title: มะพร้าวแก้ว
  discription:  กล่องละ 20 บาท ประมาณ 	5 ชิ้น
  location: ศูนย์โอทอปชุมชนเขาไมแกว
  contact: 090-134-4191
  owner: คุณวิฑูรย์
  
- product:
  id: "9"
  img: "./assets/img/product/p9.jpg"
  cat: ก๋วยเตี๋ยวเรือ
  name: ร้าน “เบญจวรรณ ก๋วยเตี๋ยวเรือต่อชาม”
  title: ก๋วยเตี๋ยวหมูสด หมูเปื่อย ลูกชิ้น ตับหมู น้ำตก ต้มยำ
  discription:  ก๋วยเตี๋ยวหมูน้ำตก ชามละ 35 บาท พิเศษ 40 บาท <br>ก๋วยเตี๋ยวหมูต้มยำ ชามละ 40 บาท พิเศษ 45 บาท
  location: ถ้ามาจากทาง ต.โป่ง ร้านอยู่ก่อนถึงวัดเขาไมแกว ติดถนนสาย 3240
  contact: 091-174-6690
  owner: คุณป่าน
  
- product:
  id: "10"
  img: "./assets/img/product/p10.jpg"
  cat: น้ำสมุนไพร
  name: ร้าน “น้ำสมุนไพรยายลอง”
  title: น้ำสมุนไพร
  discription: น้ำสมุนไพรชนิดต่างๆ ได้แก่ น้ำอัญชัน น้ำเก๊กฮวย น้ำกระเจี๊ยบ น้ำมะตูม น้ำตะไคร้
  location: ขวดละ 10 บาท
  contact: 081-267-2347
  owner: คุณลอง
  